# @package agent
_target_: agent.dqn.DQNAgent
name: dqn
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
hidden_dim: 128
device: ${device}
lr: 1e-4
gamma: 0.9
batch_size: 512
tau: 0.01
update_every_steps: 2
use_wandb: ${use_wandb}
nstep: 1
epsilon: 0.9
